name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Validate:
    strategy:
        matrix:
          os: [ubuntu-16.04, windows-latest, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install Modules
        run: npm ci

      - name: Run Lint
        run: npm run eslint

      - name: Run Unit Tests
        run: npm run test-ci
